### ISSUE TITLE
Short 'getting started' tutorial would be helpful

### ISSUE THREAD

**Issue by jasonslemons** [sikozonpc/Tile-Based-Crop-Growing-Mechanics#1]
Basically I'm new to unity(though not programming) and this is just what I was hoping to dive into.  I loaded up the project(or rather i created a unity project with these assets and created a Grid and Tilemaps) and then pained a scene and hit play and nothing happened to the crops I dropped down. I will look further at the code and the project to see what I might be missing but any help would be appreciated.  Here is about as far as I have gotten so far:
![image](https://user-images.githubusercontent.com/4845494/103389510-bcb12d80-4abb-11eb-8fa5-be3836898d05.png)

**Comment by sikozonpc** [comment]
Hey, thanks for the feedback.
Altough this repository is aimed to inspire and provide a project as a base solution and not a package, it can, however, work out of the box aswell, you have to load up the scene under `Scenes/SampleScene.unity` and just hit play.

I'll however fix compilation errors for the current versions of unity and add a little "How to run and play" section on the readme.

Also, if you want to use this project as a base project, I'll try to add a little more on the readme on this too and some comments in the code.

Feel free to submit any sugestions.

**Comment by sikozonpc** [comment]
The changes should be live now. Hope it helps.

**Comment by jasonslemons** [comment]
Thanks Tiago, I'll check this out!
